osx_image: xcode10.1
language: swift

cache: bundler

jobs:
  include:
    - stage: unit tests
      if: type = pull_request OR branch = master
      script:
        - bundle exec fastlane ios coverage
    - stage: deploy
      if: type = push AND branch = master
      script:
        - bundle exec fastlane ios pre_deploy
      after_success:
        - git config user.email "travis@travis.org"
        - git config user.name "travis-ci" # this email and name can be set anything you like
        - git push https://$GITHUB_API_TOKEN@$GH_REF --tags
        - bundle exec fastlane ios deploy
